# Generated by Django 4.2.6 on 2023-10-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product Gallery', 'verbose_name_plural': 'Product Galleries'},
        ),
        migrations.AlterModelOptions(
            name='productview',
            options={'verbose_name': 'Product View', 'verbose_name_plural': 'Product Views'},
        ),
        migrations.CreateModel(
            name='LastSeenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('fingerprint', models.CharField(max_length=250, verbose_name='Fingerprint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_seen', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Last Seen Product',
                'verbose_name_plural': 'Last Seen Products',
            },
        ),
    ]
