# Generated by Django 4.2.6 on 2023-10-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_cart_order_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
