# Generated by Django 4.2.6 on 2023-10-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bot_message_sent',
            field=models.BooleanField(default=False, verbose_name='Bot Message Sent'),
        ),
    ]
