# Generated by Django 4.2.6 on 2023-10-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_order_bot_message_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Moderatsiyada', 'In Moderation'), ('Sotildi', 'Sold'), ('Bekor qilindi', 'Canceled')], default='Moderatsiyada', max_length=250, verbose_name='Status'),
        ),
    ]
