# Generated by Django 4.2.6 on 2023-10-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('moderatsiyada', 'In Moderation'), ('sotildi', 'Sold'), ('bekor qilindi', 'Canceled')], default='moderatsiyada', max_length=250, verbose_name='Status'),
        ),
    ]
