# Generated by Django 4.2.6 on 2023-10-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_moderation', 'На модерации'), ('sold', 'Продано'), ('canceled', 'Отменено')], default='in_moderation', max_length=250, verbose_name='Status'),
        ),
    ]
