# Generated by Django 4.2.6 on 2023-10-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_stock_subtracted',
            field=models.BooleanField(default=False, verbose_name='In Stock Subtracted'),
        ),
    ]
