# Generated by Django 4.2.6 on 2023-10-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_order_in_stock_subtracted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bot_message_sent',
        ),
    ]
