# Generated by Django 4.2.6 on 2023-11-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=250, verbose_name='Status'),
        ),
    ]
