# Generated by Django 4.2.6 on 2023-11-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_cart_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedproduct',
            unique_together={('product', 'fingerprint')},
        ),
    ]
