# Generated by Django 4.2.6 on 2023-11-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_savedproduct_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Product Code'),
        ),
    ]
