# Generated by Django 4.2.6 on 2023-11-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock_count',
            field=models.PositiveIntegerField(default=1, verbose_name='In Stock Count'),
        ),
    ]
