# Generated by Django 4.2.6 on 2023-11-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_in_stock_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock_count',
            field=models.PositiveIntegerField(default=9999, verbose_name='In Stock Count'),
        ),
    ]
