# Generated by Django 4.2.6 on 2023-10-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontendTranslation',
        ),
        migrations.DeleteModel(
            name='VersionHistory',
        ),
    ]
