# Generated by Django 4.2.6 on 2023-11-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='social_media', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
